library(openxlsx)
origin <- read.xlsx("PelicanStores.xlsx",sheet="Data")
attach(origin)
summary(origin)
x11()
barplot(table(Type.of.Customer), ,main = "Type of Customer",ylab = "Number of People")
barplot(table(Items),yaxp=c(0, 30, 5),main = "Items", xlab = "The total number of items purchased",ylab = "Number of People")
boxplot(Net.Sales, yaxp=c(0, 300, 30), main = "Net Sales", ylab = "The total amount ($) charged to the credit card")
barplot(table(Method.of.Payment), cex.names = 0.8,main = "Method of Payment", ylab = "Number of People")
x11()
barplot(table(Gender),yaxp=c(0, 100, 5),main = "Gender", ylab = "Number of People")
x11()
barplot(table(Marital.Status),yaxp=c(0, 90, 9),main = " Marital Status", ylab = "Number of People")
boxplot(Age, yaxp=c(0, 80, 16), main = "Age", ylab = "The number of age")
x11()
boxplot(Net.Sales ~ Type.of.Customer , data = origin,main = "The relationship between Type of Customer and Net Sales", xlab = "Type of Customer", ylab = "The total amount ($) charged to the credit card")
x11()
fit <- lm(Net.Sales~Age, data=origin)
plot(Net.Sales~Age, ylab = "The total amount ($) charged to the credit card", main = "The relationship between Age and Net Sales") 
lines(Age, fitted(fit), col="blue")
table(Type.of.Customer)
x11()
barplot(table(Type.of.Customer, Method.of.Payment), cex.names = 0.8, yaxp=c(0, 70, 14), legend.text = c("Promotional", "Regular"), args.legend=c(x=2,y=72), main = "The relationship between Type of Customer and Method of Payment", cex.main = 0.8, ylab = "Number of people"  )
x11()
interaction.plot(Type.of.Customer,Marital.Status,Net.Sales)
